nodeLinker: pnp
enableScripts: false

yarnPath: .yarn/releases/yarn-4.4.1.cjs

packageExtensions:
  '@typescript-eslint/type-utils@*':
    peerDependencies:
      eslint: '*'
  '@typescript-eslint/utils@*':
    peerDependencies:
      typescript: '*'
  'typescript-eslint@*':
    peerDependencies:
      eslint: '*'
  '@chromatic-com/storybook@*':
    peerDependencies:
      react: '*'
  '@storybook/addon-docs@*':
    peerDependencies:
      '@types/react': '*'
  '@storybook/addon-essentials@*':
    peerDependencies:
      '@types/react': '*'
  '@storybook/react-vite@*':
    peerDependencies:
      typescript: '*'
  eslint-plugin-storybook@*:
    peerDependencies:
      typescript: '*'
