nodeLinker: pnp
enableScripts: false

yarnPath: .yarn/releases/yarn-4.4.1.cjs

packageExtensions:
  '@typescript-eslint/type-utils@*':
    peerDependencies:
      eslint: '*'
  '@typescript-eslint/utils@*':
    peerDependencies:
      typescript: '*'
  'typescript-eslint@*':
    peerDependencies:
      eslint: '*'
