name: auto_deploy

inputs:
  package:
    required: true

runs:
  using: composite
  steps:
    - name: Authenticate with Google Cloud
      id: authenticate_with_google_cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Configure Google Cloud
      id: configure_google_cloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      id: configure_docker
      run: |
        gcloud auth configure-docker ${{secrets.GCP_REGION}}-docker.pkg.dev

    - name: Docker Build and Push Image
      id: docker_build_and_push_image
      run: |
        IMAGE_NAME="${{secrets.GCP_REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/blog/0115"

        docker build -t $IMAGE_NAME:latest -f packages/blog/Dockerfile .
        docker push $IMAGE_NAME:latest

    - name: Deploy to Cloud Run
      id: deploy_to_cloud_run
      run: |
        gcloud run deploy monorepo-blog \
          --image=${{secrets.GCP_REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/blog/0115:latest \
          --region=${{secrets.GCP_REGION}} \
          --platform=managed \
          --allow-unauthenticated
