# ! blog 패키지의 ci 진행
# ! 의존성 설치 및 빌드 진행

name: blog_ci

on:
  workflow_call:

jobs:
  integration:
    name: integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v4

      - name: Setup node
        id: setup_node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn

      - name: Install dependency
        id: install_dependency
        run: |
          yarn install --immutable 2> >(tee log_${{ github.run_id }}.txt) ; \
          test ${PIPESTATUS[0]} -eq 0 || { echo "yarn install failed." ; exit 1; }

      - name: Core Build
        id: core_build
        run: |
          yarn core build 2> >(tee test_log) ; \
          test ${PIPESTATUS[0]} -eq 0 || { echo "yarn install failed." ; exit 1; }

      - name: Run Build
        id: run_build
        run: |
          yarn blog build 2> >(tee test_log) ; \
          test ${PIPESTATUS[0]} -eq 0 || { echo "yarn install failed." ; exit 1; }

      # 배포 부분은 추후에 따로 분리 예정
      # 임시로 ci 에 추가
      - name: Authenticate with Google Cloud
        id: authenticate_with_google_cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          # project_id: ${{secrets.GCP_PROJECT_ID}}

      - name: Configure Google Cloud
        id: configure_google_cloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        id: configure_docker
        run: |
          gcloud auth configure-docker ${{secrets.GCP_REGION}}-docker.pkg.dev

      - name: Docker Build and Push Image
        id: docker_build_and_push_image
        run: |
          IMAGE_NAME="${{secrets.GCP_REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/blog/0115:latest"

          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        id: deploy_to_cloud_run
        run: |
          gcloud run deploy monorepo-blog
            --image=${{secrets.GCP_REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/blog/0115:latest \
            --region=${{secrets.GCP_REGION}} \
            --platform=managed \
            --allow-unauthenticated

      - name: Upload Log File
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: workflow_logs
          path: log_${{ github.run_id }}.txt
          if-no-files-found: error
          retention-days: 1
