# ! PR을 opened, reopened, labeled, synchronize 때 CICD 워크플로우를 호출
# ! 변경된 버전의 워크플로우만 호출

name: cicd_caller

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - synchronize

# concurrency 설정 추가 예정

jobs:
  changes:
    if: github.event.pull_request.state != 'closed'
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.paths_filter.outputs.core }}
      blog: ${{ steps.paths_filter.outputs.blog }}
      portfolio: ${{ steps.paths_filter.outputs.portfolio }}

    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v3

      - name: Paths Filter
        id: paths_filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            core:
              - 'packages/core/**'
            blog:
              - 'packages/blog/**'
            portfolio: 
              - 'packages/portfolio/**'

  # blog
  blog_ci:
    needs: changes
    if: needs.changes.outputs.blog == 'true'
    uses: ./.github/workflows/blog_ci.yml
    secrets: inherit

  # core
  core_ci:
    needs: changes
    if: needs.changes.outputs.core == 'true'
    uses: ./.github/workflows/core_ci.yml
    secrets: inherit

  # portfolio
  portfolio_ci:
    needs: changes
    if: needs.changes.outputs.portfolio == 'true'
    uses: ./.github/workflows/portfolio_ci.yml
    secrets: inherit

  # 실패
  call_failure_summary:
    needs: [blog_ci, core_ci, portfolio_ci]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/failure_summary.yml
