# ! PR을 opened, reopened, labeled, synchronize 때 CICD 워크플로우를 호출
# ! 변경된 버전의 워크플로우만 호출

name: cicd_caller

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - synchronize

# concurrency 설정 추가 예정
# concurrency:

jobs:
  changes:
    if: github.event.pull_request.state != 'closed'
    runs-on: ubuntu-latest
    outputs:
      blog: ${{ steps.filter.outputs.blog }}
      portfolio: ${{ steps.filter.outputs.portfolio }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            blog:
              - 'packages/blog/**'
            portfolio: 
              - 'packages/portfolio/**'

  # blog_ci
  blog_ci:
    needs: changes
    if: needs.changes.outputs.blog == 'true'
    uses: ./.github/workflows/blog_ci.yml
    secrets: inherit
#   blog_cd
#   blog_cd:
#     needs: changes
#     if: needs.blog_ci.result == 'success' && contains(github.event.pull_request.labels.*.name, 'action:blog_cd')
#     uses: ./.github/workflows/blog_cd.yml
#     secrets: inherit
