# ! 실패한 경우 , 에러 로그를 요약해서 보여줍니다 .

name: failure_summary

on: workflow_call

jobs:
  failure_summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: workflow_logs

      - run: cat log_${{ github.run_id }}.txt > error_log

      - name: Failure Summary
        run: |
          echo '<details><summary>:boom: View error log</summary>' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "$(cat error_log)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '</details>' >> $GITHUB_STEP_SUMMARY
