# ! portfolio 패키지의 cd 진행
# ! build 체크 및 버저닝

name: portfolio_cd

on:
  workflow_call:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-latest-version.outputs.version }}
      # deployment:

    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v3

      - name: Setup node
        id: setup_node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: yarn

      - name: Install dependency
        id: install_dependency
        run: |
          yarn install --immutable 2> >(tee log_${{ github.run_id }}.txt) ; \
          test ${PIPESTATUS[0]} -eq 0 || { echo "yarn install failed." ; exit 1; }

      - name: Run Build
        id: run_build
        run: |
          yarn portfolio build 2> >(tee test_log) ; \
          test ${PIPESTATUS[0]} -eq 0 || { echo "yarn install failed." ; exit 1; }

      # - name: Deploy
      # - name: Docker

      - name: Get Latest Version
        id: get-latest-version
        uses: ./.github/actions/get_latest_version

      - name: Upload Log File
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: workflow_logs
          path: log_${{ github.run_id }}.txt
          if-no-files-found: error
          retention-days: 1
